### ISSUE TITLE
The tolerance level of new implement is too low

### ISSUE THREAD

**Issue by klauszou** [akkadotnet/HOCON#108]
I used to use the old implement of akka.hocon, recently I tried to change to the new implement, since the old one seems will no longer be updated.

But I had to say the tolerance level of new implement is too low.

First, if a key doesn't exist, then getting the value of it will always cause a exception in the new version, which in the old version, it just simply get you a null or some thing alike depends on the type, so I can just use some default value, and the user didn't have to input every key in the config. Compare with the new version, dealing the exception is just a mess.

Second,you can't simply output the config, you always got a exception on it, so you can't easily identify if there is any mis in your config.

And many other little issue. I think the change of not using Json.NET may be one of the reason, since it's compatibility is very good, and I don't get some json issue on the old one. Of course, it might be just one reason.

Almost 90% of my old config can't change to use the new version. So that I had to go back and stay with the old one. 

Pity.

**Comment by klauszou** [comment]
And a huge bug of v1.0.0 is it's hasPath() is always true

**Comment by IgorFedchenko** [comment]
Hello @klauszou 

Indeed, some important things like `config.ToString` turned out to be broken... 
I have submitted few PRs for issues I could find according to your report (great thanks for pointing out all that stuff by the way). Hope this will make library usage experience better after `v.1.2.1` release.

Also, seems like `HasPath()` is already fixed in `v.1.2.0` - or I am testing on wrong samples.

Let me know if you have more issues that prevent from using this package. Also, sharing the config that you have issues with will be appreciated.

**Comment by IgorFedchenko** [comment]
@Aaronontheweb I think we can close this issue once both PRs will be merged.

@klauszou Feel free to open new ones if you will still get any problems after v.1.2.1 release.
